name: 自动提交步数
on:
  workflow_dispatch: {}
  schedule:
    # 北京时间 8:00 -> UTC 0:00
    - cron: '0 0 * * *'
    # 北京时间 10:00 -> UTC 2:00
    - cron: '0 2 * * *'
    # 北京时间 12:00 -> UTC 4:00
    - cron: '0 4 * * *'

jobs:
  submit_steps:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 提交步数
        env:
          USERS: ${{ secrets.USERS }}
          PASSWORDS: ${{ secrets.PASSWORDS }}
          MAX_DAILY_STEPS: ${{ vars.MAX_DAILY_STEPS }}
          VARIATION_RATIO: ${{ vars.VARIATION_RATIO }}
        run: |
          python main.py "$USERS" "$PASSWORDS" 